// Code generated by cmd/reset. DO NOT EDIT.

package model

// Reset resets URLStorage to its default state.
func (r *URLStorage) Reset() {
	if r == nil {
		return
	}

	r.URLS = r.URLS[:0]
	if r.Cache != nil {
		r.Cache.Flush()
	}
	if r.ReverseCache != nil {
		r.ReverseCache.Flush()
	}
}

// Reset resets URLEnt to its default state.
func (r *URLEnt) Reset() {
	if r == nil {
		return
	}

	r.UUID = ""
	r.ShortURL = ""
	r.OriginalURL = ""
	r.UserID = ""
	r.IsDeleted = false
}

// Reset resets URLBatch to its default state.
func (r *URLBatch) Reset() {
	if r == nil {
		return
	}

	r.URLS = r.URLS[:0]
}

// Reset resets DeleteURLBatch to its default state.
func (r *DeleteURLBatch) Reset() {
	if r == nil {
		return
	}

	r.UserID = ""
	r.Batch = r.Batch[:0]
}

// Reset resets DeleteURLRecord to its default state.
func (r *DeleteURLRecord) Reset() {
	if r == nil {
		return
	}

	r.UserID = ""
	r.ShortURL = ""
}
