// Code generated by cmd/reset. DO NOT EDIT.

package audit

// Reset resets Event to its default state.
func (r *Event) Reset() {
	if r == nil {
		return
	}

	r.Timestamp = 0
	r.Action = ""
	r.UserID = ""
	r.URL = ""
}
